---
kitchen:
  log_level: debug

driver:
  name: vagrant

platforms:
<% %w(11.0.0 12.1.0).each do |chef_version| %>
- name: debian-6.0.10-<%= chef_version %>-g_i
  driver_config:
    box: opscode-debian-6.0.10
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-6.0.10_chef-provisionerless.box
    require_chef_omnibus: <%= chef_version %>
- name: debian-7.8-<%= chef_version %>-g_i
  driver_config:
    box: opscode-debian-7.8
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.8_chef-provisionerless.box
    require_chef_omnibus: <%= chef_version %>
- name: ubuntu-10.04-<%= chef_version %>-g_i
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-10.04_chef-provisionerless.box
    require_chef_omnibus: <%= chef_version %>
- name: ubuntu-12.04-<%= chef_version %>-g_i
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
    require_chef_omnibus: <%= chef_version %>
- name: ubuntu-12.10-<%= chef_version %>-g_i
  driver_config:
    box: opscode-ubuntu-12.10
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.10_chef-provisionerless.box
    require_chef_omnibus: <%= chef_version %>
- name: ubuntu-13.04-<%= chef_version %>-g_i
  driver_config:
    box: opscode-ubuntu-13.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-13.04_chef-provisionerless.box
    require_chef_omnibus: <%= chef_version %>
- name: ubuntu-13.10-<%= chef_version %>-g_i
  driver_config:
    box: opscode-ubuntu-13.10
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-13.10_chef-provisionerless.box
    require_chef_omnibus: <%= chef_version %>
- name: ubuntu-14.04-<%= chef_version %>-g_i
  driver_config:
    box: opscode-ubuntu-14.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
    require_chef_omnibus: <%= chef_version %>
- name: ubuntu-14.10-<%= chef_version %>-g_i
  driver_config:
    box: opscode-ubuntu-14.10
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.10_chef-provisionerless.box
    require_chef_omnibus: <%= chef_version %>
<% end %>

suites:
  - name: default
    run_list: &default_run_list
      - recipe[gem_installation]
    attributes: {}
  - name: gem_installation_before_convergence
    run_list:
      - recipe[gem_installation::_test_kitchen_gem_installation]
    attributes: {}
  - name: gem_installation_during_convergence
    run_list:
      - recipe[gem_installation::_test_kitchen_gem_installation_during_convergence]
    attributes: {}
  - name: dependencies_during_convergence
    run_list:
      - recipe[gem_installation::_test_kitchen_dependencies]
    attributes: {}
  - name: dependencies_during_convergence
    run_list:
      - recipe[gem_installation::test_kitchen_dependencies_before_convergence]
    attributes: {}
